services:
  mysql:
    image: mysql:8.0
    container_name: sensor-mysql
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - sensor_mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./api
    container_name: sensor-api
    restart: always
    depends_on: 
      - mysql
    ports:
      - "4000:4000"
    environment:
      TZ: America/Sao_Paulo
      API_PORT: ${API_PORT}
      DB_HOST: ${DB_HOST} 
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DEVICE_API_KEY: ${DEVICE_API_KEY}

volumes:
  sensor_mysql_data: